### ISSUE TITLE
cannot import name 'builder' from 'google.protobuf.internal'

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/earth-osm#1]
Found a nice little bug? Fill out the section below. ⬇️

**Describe the bug**
README steps are not working. Seem 

**To Reproduce**
- `conda create --name earth-osm -y`
- `conda activate earth-osm`
- ` pip install git+https://github.com/pypsa-meets-earth/earth-osm.git`
- Example CLI command: `earth_osm extract power --regions benin monaco  --features substation line`

**Screenshots**
```
earth_osm extract power --regions benin --features line
Traceback (most recent call last):                                              
  File "/home/max/.local/bin/earth_osm", line 5, in <module>
    from earth_osm.__main__ import main
  File "/home/max/.local/lib/python3.10/site-packages/earth_osm/__main__.py", line 3, in <module>
    from .args import main  # pragma: no cover
  File "/home/max/.local/lib/python3.10/site-packages/earth_osm/args.py", line 15, in <module>
    from earth_osm.eo import get_osm_data
  File "/home/max/.local/lib/python3.10/site-packages/earth_osm/eo.py", line 15, in <module>
    from earth_osm.filter import get_filtered_data
  File "/home/max/.local/lib/python3.10/site-packages/earth_osm/filter.py", line 13, in <module>
    from earth_osm.extract import filter_pbf
  File "/home/max/.local/lib/python3.10/site-packages/earth_osm/extract.py", line 13, in <module>
    from earth_osm.osmpbf import Node, Way, Relation, osmformat_pb2
  File "/home/max/.local/lib/python3.10/site-packages/earth_osm/osmpbf/osmformat_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/usr/lib/python3/dist-packages/google/protobuf/internal/__init__.py)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 22

**Comment by pz-max** [comment]
Fix: `pip install --upgrade protobuf`... 
Not sure why protobuf was not correctly installed from the `earth-osm` installation process

**Comment by mnm-matin** [comment]
@b158156 solves this
