### ISSUE TITLE
Incompatibility of convert_pd_to_gdf_lines with Shapely 2.0

### ISSUE THREAD

**Issue by davide-f** [pypsa-meets-earth/earth-osm#28]
**Describe the bug**

When extracting data for Kazhakhstan a lonlat conversion problem arises
With the new version of shapely, lon-lat data shall be passed as tuples, not lists. Forcing the entries to be tuples should be enough.

``` bash
INFO:osm_data_extractor:Writing GeoJSON file
WARNING:osm_data_extractor:Node dataframe not empty for line in KZ
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpiy9bx29f.download_osm_data.py", line 110, in <module>
    eo.get_osm_data(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/earth_osm/eo.py", line 103, in get_osm_data
    output_creation(df_feature, primary_name, feature_name, [region], data_dir, out_format, out_aggregate)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/earth_osm/utils.py", line 204, in output_creation
    gdf_feature = convert_pd_to_gdf_lines(df_feature)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/earth_osm/utils.py", line 132, in convert_pd_to_gdf_lines
    df_way, geometry=[LineString(x) for x in df_way.lonlat], crs="EPSG:4326"
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/earth_osm/utils.py", line 132, in <listcomp>
    df_way, geometry=[LineString(x) for x in df_way.lonlat], crs="EPSG:4326"
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/shapely/geometry/linestring.py", line 73, in __new__
    geom = shapely.linestrings(coordinates)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/shapely/decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/shapely/creation.py", line 120, in linestrings
    return lib.linestrings(coords, out=out, **kwargs)
```

When debugging for Russia (anotherwone) appeared that in some cases the data in osm contain unexpected values.
In particular, in the lines dataseta, a node was improperly stored.
That problem was solved using

`df_way = df_way.drop(df_way[df_way.Type != "Way"].index).reset_index(drop=True)`

**To Reproduce**
1. Run pypsa-earth for kazakhstan or download data for kazakhstan
**Desktop (please complete the following information):**
 - OS:  Linux

**Comment by mnm-matin** [comment]
the way we handle nodes and ways will be changing see the branch config-revamp. these thing will be tackled there.
